spring:
    database: H2

    h2:
        console:
            enabled: true
            path: /h2

    datasource:
        url: jdbc:h2:mem:test
        username: sa
        password: sa
        driver-class-name: org.h2.Driver

    jpa:
        hibernate:
            use-new-id-generator-mappings: false
        properties:
            hibernate:
                pool_size: 50    
        